version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5016:5016"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://debt-a-way-db_owner:8FBCgkub7XMi@ep-wild-paper-a5uiskpr.us-east-2.aws.neon.tech/debt-a-way-db?sslmode=require

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: debt-a-way-db_owner
      POSTGRES_PASSWORD: 8FBCgkub7XMi
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
